apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: dev
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nanajanashia/argocd-app:1.0 #1.0, 1.1, 1.2
        #image: wil42/playground:v1 #v1, v2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: dev
spec:
  ports:
  #- port: 80
  - port: 8080
    targetPort: 8080
    protocol: TCP
    #name: http
  selector:
    app: myapp
