apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: dev
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        #image: nanajanashia/argocd-app:1.0 #1.0, 1.1, 1.2
        image: wil42/playground:v2 #v1, v2
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  namespace: dev
spec:
  ports:
  #- port: 80
  - port: 8888
    targetPort: 8888
    protocol: TCP
    nodePort: 30080 #added
    #name: http
  selector:
    app: myapp
  type: NodePort #added  
