apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: dev
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        #image: nanajanashia/argocd-app:1.0 #1.0, 1.1, 1.2
        image: wil42/playground:v1 #v1, v2
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  namespace: dev
spec:
  ports:
  #- port: 80
  - port: 8888
    targetPort: 8888
    protocol: TCP
    #nodePort: 30080 #added=====working
    #name: http
  selector:
    app: myapp
  #type: NodePort #added=====working  
  #url added =====working
  #https://stackoverflow.com/questions/76324359/problem-setting-up-an-ingress-traefik-to-be-able-to-reach-host-port-8888-with-k3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: dev
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myapp-svc
            namespace: dev
            port:
              number: 8888
